<a href="https://colab.research.google.com/github/nayoung718/essa_python_1/blob/main/4_5_%EC%84%B8%EC%85%98_%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%B6%84%EC%84%9D_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 아래의 데이터를 이용하여 공부한 내용을 바탕으로 문제 2개를 만들고 답하세요.

In [1]:
import nltk
nltk.download("book", quiet=True)
from nltk.book import *

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [2]:
# 파일 목록 확인
nltk.corpus.gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [3]:
emma = nltk.corpus.gutenberg.raw('austen-emma.txt')
print(emma[:5000])

[Emma by Jane Austen 1816]

VOLUME I

CHAPTER I


Emma Woodhouse, handsome, clever, and rich, with a comfortable home
and happy disposition, seemed to unite some of the best blessings
of existence; and had lived nearly twenty-one years in the world
with very little to distress or vex her.

She was the youngest of the two daughters of a most affectionate,
indulgent father; and had, in consequence of her sister's marriage,
been mistress of his house from a very early period.  Her mother
had died too long ago for her to have more than an indistinct
remembrance of her caresses; and her place had been supplied
by an excellent woman as governess, who had fallen little short
of a mother in affection.

Sixteen years had Miss Taylor been in Mr. Woodhouse's family,
less as a governess than a friend, very fond of both daughters,
but particularly of Emma.  Between _them_ it was more the intimacy
of sisters.  Even before Miss Taylor had ceased to hold the nominal
office of governess, the mildness o

### (1) 문제 1 : CountVectorizer를 이용해 BOW 피처 벡터화하여 문장별 단어 개수를 많은 순으로 출력하고 단어별 총 출현 횟수도 출력하시오.

In [15]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize,sent_tokenize

In [16]:
emma = nltk.corpus.gutenberg.raw('austen-emma.txt')

# 텍스트를 문장으로 분할
sentences = sent_tokenize(emma)

# 문장별로 토큰화하여 리스트로 저장
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

# CountVectorizer
vectorizer = CountVectorizer()

# 문장 리스트를 BOW 표현으로 변환
bow_representation = vectorizer.fit_transform([' '.join(sentence) for sentence in tokenized_sentences])

# 특성 이름을 가져옴 (어휘 사전에 있는 단어들)
feature_names = vectorizer.get_feature_names_out()

# BOW 표현을 배열로 변환
bow_array = bow_representation.toarray()

# 특성 이름과 BOW 배열을 출력
print("특성 이름:", feature_names)
print("BOW 배열:", bow_array)

특성 이름: ['000' '10' '1816' ... 'youthful' 'zeal' 'zigzags']
BOW 배열: [[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
# CountVectorizer의 vocabulary를 이용하여 정렬된 형태의 DataFrame
countvect_df = pd.DataFrame(bow_array, columns=sorted(vectorizer.vocabulary_.keys()))

# 열 기준으로 합계를 구하여 많이 나온 순으로 정렬
countvect_df_sum = countvect_df.sum(axis=0)

# 많이 나온 순으로 정렬된 DataFrame을 출력
sorted_countvect_df = countvect_df[countvect_df_sum.sort_values(ascending=False).index]
print(sorted_countvect_df)

print("-------------")

# 단어별로 총 출현 횟수를 출력
total_word_counts = countvect_df_sum.sort_values(ascending=False)
print("단어별 총 출현 횟수:")
print(total_word_counts)

      to  the  and  of  it  her  was  she  not  in  ...  impediment  impelled  \
0      2    2    3   2   0    1    0    0    0   1  ...           0         0   
1      0    2    1   4   0    1    1    1    0   1  ...           0         0   
2      1    0    1   2   0    4    0    0    0   1  ...           0         0   
3      0    0    0   2   0    0    0    0    0   1  ...           0         0   
4      0    1    0   1   1    0    1    0    0   0  ...           0         0   
...   ..  ...  ...  ..  ..  ...  ...  ...  ...  ..  ...         ...       ...   
7488   0    2    1   2   0    0    1    0    0   2  ...           0         0   
7489   3    4    3   3   0    1    3    1    0   0  ...           0         0   
7490   1    3    2   1   2    2    1    1    0   0  ...           0         0   
7491   0    8    0   4   0    0    0    0    0   2  ...           0         0   
7492   0    0    0   0   0    0    0    0    0   0  ...           0         0   

      impending  impertinen

### (2) 문제 2 : TfidfVectorizer를 이용해 BOW 피처 벡터화하여 문장별 단어 개수를 많은 순으로 출력하고 단어별 총 출현 횟수도 출력하시오.

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
emma = nltk.corpus.gutenberg.raw('austen-emma.txt')

# 텍스트를 문장으로 분할
sentences = sent_tokenize(emma)

# 문장별로 토큰화하여 리스트로 저장
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

# TfidfVectorizer
vectorizer = TfidfVectorizer()

# 문장 리스트를 TF-IDF 표현으로 변환
tfidf_representation = vectorizer.fit_transform([' '.join(sentence) for sentence in tokenized_sentences])

# 특성 이름을 가져옴 (어휘 사전에 있는 단어들)
feature_names = vectorizer.get_feature_names_out()


# TF-IDF 표현을 배열로 변환
tfidf_array = tfidf_representation.toarray()

# TF-IDF 배열을 출력
print("TF-IDF 배열:", tfidf_array)

TF-IDF 배열: [[0.         0.         0.24286186 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [25]:

# TfidfVectorizer의 vocabulary를 이용하여 정렬된 형태의 DataFrame
tfidf_df = pd.DataFrame(tfidf_array, columns=sorted(vectorizer.vocabulary_.keys()))

# 열 기준으로 합계를 구하여 TF-IDF 값이 높은 순으로 정렬
tfidf_df_sum = tfidf_df.sum(axis=0)

# TF-IDF 값이 높은 순으로 정렬된 DataFrame을 출력
sorted_tfidf_df = tfidf_df[tfidf_df_sum.sort_values(ascending=False).index]
print(sorted_tfidf_df)

# 단어별로 TF-IDF 값의 총합을 출력
total_tfidf_values = tfidf_df_sum.sort_values(ascending=False)
print("단어별 총 TF-IDF 값:")
print(total_tfidf_values)

            to       the       and        of  you        it  not       she  \
0     0.098853  0.103905  0.154941  0.107424  0.0  0.000000  0.0  0.000000   
1     0.000000  0.140185  0.069681  0.289868  0.0  0.000000  0.0  0.090887   
2     0.053079  0.000000  0.055464  0.115363  0.0  0.000000  0.0  0.000000   
3     0.000000  0.000000  0.000000  0.169606  0.0  0.000000  0.0  0.000000   
4     0.000000  0.128479  0.000000  0.132831  0.0  0.152594  0.0  0.000000   
...        ...       ...       ...       ...  ...       ...  ...       ...   
7488  0.000000  0.155989  0.077536  0.161273  0.0  0.000000  0.0  0.000000   
7489  0.146419  0.205202  0.152998  0.159115  0.0  0.000000  0.0  0.066520   
7490  0.043640  0.137610  0.091201  0.047424  0.0  0.108960  0.0  0.059478   
7491  0.000000  0.432579  0.000000  0.223616  0.0  0.000000  0.0  0.000000   
7492  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.000000   

           was       her  ...  hautboy  sorts  hautboys  cultiv

그 둘의 차이점은?

CountVectorizer는 각 단어의 출현 빈도를 사용하여 문서를 표현, TfidfVectorizer는 단어의 출현 빈도 뿐만 아니라 해당 단어가 다른 문서에 출현하는 빈도에 대한 정보도 고려하여 단어의 중요도를 계산

# 2. 조원들과 만든 문제와 답을 공유해보세요.